FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV GITHUB_REF_NAME=dev
RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist-next ./dist-next
COPY --from=builder /app/server-next.js ./

EXPOSE 4322

CMD ["node", "server-next.js"]
