# Backend configuration: Connects to your GitHub repository
backend:
  name: github
  repo: your-username/your-repo-name # !!! IMPORTANT: Replace with your repo path (e.g., william64/william64.com) !!!
  branch: main # Or whichever branch you deploy from (usually 'main' or 'master')
  # Optional: Uncomment and configure if using GitHub Enterprise
  # base_url: https://github.your-company.com
  # auth_endpoint: api/auth

# Local backend useful for testing configuration without pushing to GitHub
# local_backend: true # Uncomment this for local testing only

# Media files configuration (optional, but recommended for images)
media_folder: "public/uploads" # Where images uploaded via the CMS are stored (relative to project root)
public_folder: "/uploads" # The public URL path for accessing media files (relative to site root)

# Content Collections Definition
collections:
  - name: "posts" # Internal identifier for the collection
    label: "Blog Posts" # Display name in the CMS UI
    folder: "src/pages/posts" # Path to the folder containing blog post files (relative to project root)
    create: true # Allow creating new posts via the CMS
    slug: "{{slug}}" # Generates filename from the 'Title' field (e.g., my-awesome-post)
    extension: "mdx" # File extension for new posts
    format: "frontmatter" # Specifies files have frontmatter + body
    fields: # Defines the form fields in the CMS UI for each post
      - { label: "Title", name: "title", widget: "string" } # Maps to frontmatter 'title'
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false } # Maps to 'date', ensures YYYY-MM-DD format
      - { label: "Summary", name: "summary", widget: "text" } # Maps to 'summary'
      - { label: "Body", name: "body", widget: "markdown" } # Maps to the main content below frontmatter
