# public/admin/config.yml

backend:
  name: github
  # Required: Specify your GitHub repository path
  repo: suttonwilliamd/William64.com
  # Required: Specify the branch to work with
  branch: main
  # Required for client-side GitHub auth: Use 'pkce'
  auth_type: pkce
  # Required for client-side GitHub auth: Your GitHub OAuth App Client ID
  # Replace the placeholder below with your actual Client ID
  app_id: Ov23licororpp5wCIsNN

# Optional: Configure media storage
media_folder: "public/uploads" # Where media files will be stored in the repo
public_folder: "/uploads"      # The public URL path for accessing media files

# Required: Define your content collections
collections:
  - name: "posts"               # Used in routes, e.g., /admin/#/collections/posts
    label: "Blog Posts"         # Used in the UI
    folder: "src/pages/posts"   # The path to the folder where documents are stored
    create: true                # Allow users to create new documents in this collection
    slug: "{{slug}}"            # Filename template, uses the title field
    extension: "mdx"            # File extension for new posts
    format: "frontmatter"       # Specifies the format, using YAML frontmatter
    fields:                     # The fields for each document, usually in frontmatter
      # Hidden field to automatically set the layout for new posts
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/PostLayout.astro" }
      # Standard fields matching your MDX frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Summary", name: "summary", widget: "text" } # Use 'text' for multi-line summary
      - { label: "Body", name: "body", widget: "markdown" }  # The main content, processed as Markdown
